# -*- coding: utf-8 -*-
"""DetroitBlinkTicket.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1-GM6hOlQn6_fHax4i3Nv1yFCJhFuaGmw
"""

#Importing libraries
import numpy as np
import pandas as pd

#Loading data

#Data Exploration/Analysis

#Data Preprocessing